version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: upds_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 12345678
      DB_NAME: upds_db
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app

volumes:
  db_data:
